domain: https://ldmobilex.github.io/
url: https://ldmobilex.github.io/
baseurl: ""

title: Lisa
email: ld3216@columbia.edu
author: Lisa DiSalvo

lang: en

plugins:
  - jekyll-seo-tag

color: "#13ccf9"
# disqus:
#   shortname: example-com
#
rrss:
  email: "ld3126@columbia.edu"
  telegram: "https://t.me/"
  discord: "lunarheightssx"
